# Numpy basics

In [5]:
%pip install numpy

     -------------------------------------- 14.8/14.8 MB 772.6 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\blanc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

# Creando arreglos

In [5]:
print('# vector con 10 ceros')
x = np.zeros(10)
display(x)

print('# vector con 5 unos')
x = np.ones(5)
display(x)

print('# vector con rango de numeros entre 40 y 55 (no inclusive)')
x = np.arange(40,55)
display(x)

print('# vector con 10 números equiespaciados entre 0 y 1')
x = np.linspace(0,1,10)
display(x)

print('# vector aleatorio de 10 números entre 0 y 1')
x = np.random.rand(10)
display(x)

print('# probemos con arreglos bidimencionales o matrices')
x = np.random.rand(3,4)
display(x)

# vector con 10 ceros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# vector con 5 unos


array([1., 1., 1., 1., 1.])

# vector con rango de numeros entre 40 y 55 (no inclusive)


array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

# vector con 10 números equiespaciados entre 0 y 1


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# vector aleatorio de 10 números entre 0 y 1


array([0.7869521 , 0.05773551, 0.11088003, 0.07584425, 0.60734091,
       0.90940095, 0.15828708, 0.13814963, 0.71945988, 0.66334911])

# probemos con arreglos bidimencionales o matrices


array([[0.81311435, 0.71091179, 0.71836014, 0.35174892],
       [0.34705693, 0.05259555, 0.97193674, 0.76235089],
       [0.2369444 , 0.13660004, 0.23357988, 0.45702961]])

## Operaciones entre arreglos

`numpy` opera bajo las operaciones tradicionales entre arreglos.

In [6]:
print('# operaciones entre vectores y números')
x = np.arange(10)
display(x, x*10)

print('# operaciones entre vectores')
x = np.ones(10)
y = np.random.rand(10)
display(x,y,x + y)

print('# aplicar funciones a vectores')
x = np.linspace(0,1,10)  # 
y = np.sin(2*np.pi*x)
display(x,y)

# operaciones entre vectores y números


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# operaciones entre vectores


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([0.58037149, 0.28730371, 0.01881533, 0.57590355, 0.85877269,
       0.16344336, 0.77386127, 0.23845376, 0.99207878, 0.8741389 ])

array([1.58037149, 1.28730371, 1.01881533, 1.57590355, 1.85877269,
       1.16344336, 1.77386127, 1.23845376, 1.99207878, 1.8741389 ])

# aplicar funciones a vectores


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [ ]:
x = np.zeros((3,3))
display(x)

print('# asignando un valor en la fila 2 y la columna 3')
x[1,2] = 1
display(x)

print('# asignando un valor a todos los elementos de la fila 0')
x[0,:] = 2
display(x)

print('# asignando un valor a todos los elementos de la columna 0')
x[:,0] = 3
display(x)

print('# asignando con lista de índices')
x[[0,2],[2,1]] = 4
display(x)

print('# asignando con mascaras booleanas')
x[x==4] = 5
display(x)