In [1]:
import numpy as np


# Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

Many ufuncs are simple element-wise transformations, like sqrt or exp:


In [2]:
x = np.arange(start=0, stop=12)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x = np.sqrt(x)
x


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays (thus, binary ufuncs) and return a single array as the result:


In [4]:
x = np.random.randn(1, 3)
y = np.random.randn(1, 3)
x, y


(array([[-0.58963252, -0.603893  , -0.47095728]]),
 array([[-0.33393137, -0.76835324, -3.30166471]]))

In [5]:
z = np.maximum(x, y)
z


array([[-0.33393137, -0.603893  , -0.47095728]])

In [6]:
remainder, whole = np.modf(x)
remainder, whole


(array([[-0.58963252, -0.603893  , -0.47095728]]), array([[-0., -0., -0.]]))

| Function                                                     | Description                                                                                                     |
| :----------------------------------------------------------- | :-------------------------------------------------------------------------------------------------------------- |
| `abs, fabs`                                                  | Compute the absolute value element-wise for integer, floating-point, or complex values                          |
| `sqrt`                                                       | Compute the square root of each element (equivalent to `arr ** 0.5`)                                            |
| `square`                                                     | Compute the square of each element (equivalent to `arr ** 2`)                                                   |
| `exp`                                                        | Compute the exponent ex of each element                                                                         |
| `log, log10, log2, log1p`                                    | Natural logarithm (base _e_), log base 10, log base 2, and log(1 + x), respectively                             |
| `sign`                                                       | Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)                                      |
| `ceil`                                                       | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)           |
| `floor`                                                      | Compute the floor of each element (i.e., the largest integer less than or equal to each element)                |
| `rint`                                                       | Round elements to the nearest integer, preserving the `dtype`                                                   |
| `modf`                                                       | Return fractional and integral parts of array as a separate array                                               |
| `isnan`                                                      | Return boolean array indicating whether each value is `NaN` (Not a Number)                                      |
| `isfinite, isinf`                                            | Return boolean array indicating whether each element is finite (non-`inf`, non-`NaN`) or infinite, respectively |
| `cos, cosh, sin, sinh, tan, tanh`                            | Regular and hyperbolic trigonometric functions                                                                  |
| `arccos, arccosh, arcsin, arcsinh, arctan, arctanh`          | Inverse trigonometric functions                                                                                 |
| `logical_not`                                                | Compute truth value of `not x` element-wise (equivalent to `~arr`).                                             |
| `add`                                                        | Add corresponding elements in arrays                                                                            |
| `subtract`                                                   | Subtract elements in second array from first array                                                              |
| `multiply`                                                   | Multiply array elements                                                                                         |
| `divide, floor_divide`                                       | Divide or floor divide (truncating the remainder)                                                               |
| `power`                                                      | Raise elements in first array to powers indicated in second array                                               |
| `maximum, fmax`                                              | Element-wise maximum; `fmax` ignores `NaN`                                                                      |
| `minimum, fmin`                                              | Element-wise minimum; `fmin` ignores `NaN`                                                                      |
| `mod`                                                        | Element-wise modulus (remainder of division)                                                                    |
| `copysign`                                                   | Copy sign of values in second argument to values in first argument                                              |
| `greater, greater_equal, less, less_equal, equal, not_equal` | Perform element-wise comparison, yielding boolean array (equivalent to infix operators `>, >=, <, <=, ==, !=`)  |
| `logical_and, logical_or, logical_xor`                       | Compute element-wise truth value of logical operation (equivalent to infix operators `& \| , ^`)                |
