In [15]:
import numpy as np


# Expressing Conditional Logic as Array Operations

The numpy.where function is a vectorized version of the ternary expression x if condition else y. Suppose we wanted to take a value from xarr whenever the corresponding value in cond is True, and otherwise take the value from yarr.


In [16]:
xarr = np.arange(start=1.1, step=0.1, stop=1.6)
yarr = np.arange(start=2.1, step=0.1, stop=2.6)
cond = np.array([True, False, True, True, False])
xarr, yarr, cond


(array([1.1, 1.2, 1.3, 1.4, 1.5]),
 array([2.1, 2.2, 2.3, 2.4, 2.5]),
 array([ True, False,  True,  True, False]))

With np.where you can write this very concisely:


In [17]:
result = np.where(cond, xarr, yarr)
result


array([1.1, 2.2, 1.3, 1.4, 2.5])

The second and third arguments to np.where don’t need to be arrays; one or both of them can be scalars. A typical use of where in data analysis is to produce a new array of values based on another array. Suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 2 and all negative values with –2. This is very easy to do with np.where:


In [18]:
m = np.random.randn(4, 4)
m


array([[ 0.56477632, -0.83296765,  0.11340605,  0.45627625],
       [ 1.09754627, -0.51709855, -0.23764989,  0.91761604],
       [ 0.70965609,  1.26222344,  0.40078502, -0.58774101],
       [-0.15440465,  0.73497019, -1.14298642,  0.37199666]])

In [19]:
result = np.where(m > 0, 2, -2)
result


array([[ 2, -2,  2,  2],
       [ 2, -2, -2,  2],
       [ 2,  2,  2, -2],
       [-2,  2, -2,  2]])

You can combine scalars and arrays when using np.where. For example, I can replace all positive values in arr with the constant 2 like so:


In [20]:
result = np.where(m > 0, 2, m)
result


array([[ 2.        , -0.83296765,  2.        ,  2.        ],
       [ 2.        , -0.51709855, -0.23764989,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.58774101],
       [-0.15440465,  2.        , -1.14298642,  2.        ]])

# Mathematical and Statistical Methods

A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class. You can use aggregations (often called reductions) like sum, mean, and std (standard deviation) either by calling the array instance method or using the top-level NumPy function.

Here I generate some normally distributed random data and compute some aggregate statistics:


In [21]:
arr = np.random.randn(5, 4)
arr


array([[-1.1354769 , -0.48978961,  0.76804497, -1.11897213],
       [-1.36503729, -1.50580294,  1.97442652, -0.97159495],
       [-1.55358628, -0.01695896, -0.54869175,  1.12179302],
       [-0.79947024, -1.60634224,  1.29081576,  1.24115984],
       [-0.58440398,  0.11506659, -0.15008582, -0.37541367]])

In [22]:
sum = arr.sum()
sum


-5.710320051091419

In [23]:
sum = arr.sum(axis=0)
sum


array([-5.4379747 , -3.50382715,  3.33450967, -0.10302787])

In [24]:
mean = arr.mean(axis=1)
mean


array([-0.49404842, -0.46700217, -0.24936099,  0.03154078, -0.24870922])

Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:


In [25]:
arr = np.arange(start=0, stop=8)
arr


array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
acum = arr.cumsum()
acum


array([ 0,  1,  3,  6, 10, 15, 21, 28])

| Method           | Description                                                                                                          |
| :--------------- | :------------------------------------------------------------------------------------------------------------------- |
| `sum`            | Sum of all the elements in the array or along an axis; zero-length arrays have sum 0                                 |
| `mean`           | Arithmetic mean; zero-length arrays have `NaN` mean                                                                  |
| `std, var`       | Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator `n`) |
| `min, max`       | Minimum and maximum                                                                                                  |
| `argmin, argmax` | Indices of minimum and maximum elements, respectively                                                                |
| `cumsum`         | Cumulative sum of elements starting from 0                                                                           |
| `cumprod`        | Cumulative product of elements starting from 1                                                                       |
