In [15]:
import numpy as np


# Expressing Conditional Logic as Array Operations

The numpy.where function is a vectorized version of the ternary expression x if condition else y. Suppose we wanted to take a value from xarr whenever the corresponding value in cond is True, and otherwise take the value from yarr.


In [16]:
xarr = np.arange(start=1.1, step=0.1, stop=1.6)
yarr = np.arange(start=2.1, step=0.1, stop=2.6)
cond = np.array([True, False, True, True, False])
xarr, yarr, cond


(array([1.1, 1.2, 1.3, 1.4, 1.5]),
 array([2.1, 2.2, 2.3, 2.4, 2.5]),
 array([ True, False,  True,  True, False]))

With np.where you can write this very concisely:


In [17]:
result = np.where(cond, xarr, yarr)
result


array([1.1, 2.2, 1.3, 1.4, 2.5])

The second and third arguments to np.where don’t need to be arrays; one or both of them can be scalars. A typical use of where in data analysis is to produce a new array of values based on another array. Suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 2 and all negative values with –2. This is very easy to do with np.where:


In [18]:
m = np.random.randn(4, 4)
m


array([[ 0.56477632, -0.83296765,  0.11340605,  0.45627625],
       [ 1.09754627, -0.51709855, -0.23764989,  0.91761604],
       [ 0.70965609,  1.26222344,  0.40078502, -0.58774101],
       [-0.15440465,  0.73497019, -1.14298642,  0.37199666]])

In [19]:
result = np.where(m > 0, 2, -2)
result


array([[ 2, -2,  2,  2],
       [ 2, -2, -2,  2],
       [ 2,  2,  2, -2],
       [-2,  2, -2,  2]])

You can combine scalars and arrays when using np.where. For example, I can replace all positive values in arr with the constant 2 like so:


In [20]:
result = np.where(m > 0, 2, m)
result


array([[ 2.        , -0.83296765,  2.        ,  2.        ],
       [ 2.        , -0.51709855, -0.23764989,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.58774101],
       [-0.15440465,  2.        , -1.14298642,  2.        ]])

# Mathematical and Statistical Methods

A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class. You can use aggregations (often called reductions) like sum, mean, and std (standard deviation) either by calling the array instance method or using the top-level NumPy function.

Here I generate some normally distributed random data and compute some aggregate statistics:


In [47]:
arr = np.random.randn(5, 4)
arr


array([[ 0.56793846,  1.27864262,  0.1883715 , -0.62020253],
       [-0.51293121,  1.60128504,  0.89686051,  0.96091747],
       [ 0.69677674, -0.63410099,  1.11932744, -0.60958382],
       [ 0.76627384,  2.19544766, -0.10993321,  0.40191377],
       [-0.84597933,  0.03324655, -0.94525661,  0.5903422 ]])

In [48]:
sum = arr.sum()
sum


7.0193560770249865

In [49]:
sum_a = arr.sum(axis=0)
sum_b = np.sum(a=arr, axis=0)
sum_a , sum_b 


(array([0.67207849, 4.47452088, 1.14936963, 0.72338708]),
 array([0.67207849, 4.47452088, 1.14936963, 0.72338708]))

In [50]:
mean_a = arr.mean(axis=1)
mean_b = np.mean(a=arr, axis=1)
mean_a, mean_b


(array([ 0.35368751,  0.73653295,  0.14310484,  0.81342551, -0.2919118 ]),
 array([ 0.35368751,  0.73653295,  0.14310484,  0.81342551, -0.2919118 ]))

Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:


In [51]:
arr = np.arange(start=0, stop=8)
arr


array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
acum = arr.cumsum()
acum


array([ 0,  1,  3,  6, 10, 15, 21, 28])

| Method           | Description                                                                                                          |
| :--------------- | :------------------------------------------------------------------------------------------------------------------- |
| `sum`            | Sum of all the elements in the array or along an axis; zero-length arrays have sum 0                                 |
| `mean`           | Arithmetic mean; zero-length arrays have `NaN` mean                                                                  |
| `std, var`       | Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator `n`) |
| `min, max`       | Minimum and maximum                                                                                                  |
| `argmin, argmax` | Indices of minimum and maximum elements, respectively                                                                |
| `cumsum`         | Cumulative sum of elements starting from 0                                                                           |
| `cumprod`        | Cumulative product of elements starting from 1                                                                       |


# Methods for Boolean Arrays
Boolean values are coerced to 1 (True) and 0 (False) in the preceding methods. Thus, sum is often used as a means of counting True values in a boolean array:

In [53]:
arr = np.random.randn(10)
arr

array([ 0.88628354, -1.39366831,  0.13907064,  0.79223286, -1.44503162,
       -0.38156673, -1.24904938,  0.13722786,  0.28174414, -1.47852378])

In [54]:
(arr > 0).sum()

5

There are two additional methods, any and all, useful especially for boolean arrays. any tests whether one or more values in an array is True, while all checks if every value is True:

In [55]:
bools = arr > 0
bools

array([ True, False,  True,  True, False, False, False,  True,  True,
       False])

In [56]:
np.any(arr > 0)

True

In [57]:
np.all(arr > 0)

False